version: '3.8'

services:
  php:
    platform: linux/x86_64
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html:rw,delegated
    command: sh -c "composer install && php artisan serve --host=0.0.0.0"
    ports:
      - "8000:8000"
    environment:
      TZ: Asia/Tokyo
      APP_URL: http://host.docker.internal
    tty: true

  node:
    platform: linux/x86_64
    build:
      context: .
      dockerfile: Dockerfile.node
    volumes:
      - .:/app:rw,delegated
    working_dir: "/app"
    command: sh -c "npm install && npm run dev"
    ports:
      - "3000:3000"
      - "5173:5173"
    environment:
      TZ: Asia/Tokyo
    user: node
    tty: true
