version: '3.8'

services:
  php:
    platform: linux/x86_64
    build:
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - ..:/var/www/html:rw,delegated
    command: sh -c "composer install && php artisan serve --host=0.0.0.0"
    ports:
      - "8000:8000"
    environment:
      TZ: Asia/Tokyo
      APP_URL: http://localhost:8000
    tty: true

  node:
    platform: linux/x86_64
    build:
      context: ./node
      dockerfile: Dockerfile
    volumes:
      - ..:/app:rw,delegated
    working_dir: "/app"
    command: sh -c "npm install && npm run dev"
    ports:
      - "3000:3000"
      - "5173:5173"
    environment:
      TZ: Asia/Tokyo
    user: node
    tty: true

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:

